# Use nginx as HTTP proxy
etfproxy:
 image: nginx
 restart: unless-stopped
 volumes:
  - ./nginx.conf:/etc/nginx/nginx.conf:ro
  - ./htpasswd.txt:/etc/nginx/.htpasswd:ro
 log_driver: "json-file"
 log_opt:
  max-size: "5000k"
  max-file: "5"
 ports:
  - "80:80"
 links:
  - etfwebapp

etfwebapp:
 image: iide/etf-webapp
 restart: unless-stopped
 volumes:
  - /etf/testdata:/etf/testdata
  - /etf/ds/obj:/etf/ds/obj
  - /etf/ds/appendices:/etf/ds/appendices
  - /etf/ds/db/data:/etf/ds/db/data
  - /etf/http_uploads:/etf/http_uploads
  - /etf/projects:/etf/projects
  - /etf/bak:/etf/bak
  - ./etf-config.properties:/etf/etf-config.properties:ro
  # Reports and test drivers are stored in the container
 log_driver: "json-file"
 env_file:
  - ./etfwebapp.env
 log_opt:
  max-size: "5000k"
  max-file: "5"
