# Use nginx as HTTP proxy
etfproxy:
 image: nginx
 restart: unless-stopped
 volumes:
  - ./nginx.conf:/etc/nginx/nginx.conf:ro
  - ./htpasswd.txt:/etc/nginx/.htpasswd:ro
 log_driver: "json-file"
 log_opt:
  max-size: "5000k"
  max-file: "5"
 ports:
  - "80:80"
 links:
  - etfwebapp

etfwebapp:
 image: iide/etf-webapp
 restart: unless-stopped
 environment:
  # - ETF_TESTPROJECTS_ZIP=https://github.com/.../master.zip
  # - PROJECT_DIRECTORY_NAME=custom-ets
 volumes:
  - /etf/testdata:/etf/testdata
  - /etf/http_uploads:/etf/http_uploads
  - /etf/projects:/etf/projects
  - /etf/bak:/etf/bak
  - /etf/logs:/etf/logs
  # Reports and test drivers are stored in the container
  # - /etf/ds:/etf/ds
  # - /etf/projects:/ets/projects
 log_driver: "json-file"
 log_opt:
  max-size: "5000k"
  max-file: "5"
